-- MySQL Script generated by MySQL Workbench
-- Wed Sep 12 21:38:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sapi` DEFAULT CHARACTER SET utf8 ;
USE `sapi` ;

-- -----------------------------------------------------
-- Table `sapi`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`, `idEstado`),
  INDEX `fk_Ciudad_Estado_idx` (`idEstado` ASC),
  CONSTRAINT `fk_Ciudad_Estado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `sapi`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadoCivil` (
  `idEstadoCivil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idEstadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `primerApellido` VARCHAR(127) NOT NULL,
  `segundoApellido` VARCHAR(127) NULL,
  `curp` VARCHAR(18) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(64) NULL,
  `fechaNaciemiento` DATE NULL,
  `idMunicipio` INT NOT NULL,
  `idEstadoCivil` INT NOT NULL,
  `idRol` INT NOT NULL,
  `edad` INT NULL,
  `imagen` MEDIUMBLOB NULL,
  PRIMARY KEY (`idPersona`, `idRol`),
  INDEX `fk_Persona_Ciudad1_idx` (`idMunicipio` ASC),
  INDEX `fk_Persona_EstadoCivil1_idx` (`idEstadoCivil` ASC),
  INDEX `fk_Persona_Rol1_idx` (`idRol` ASC),
  CONSTRAINT `fk_Persona_Ciudad1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `sapi`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_EstadoCivil1`
    FOREIGN KEY (`idEstadoCivil`)
    REFERENCES `sapi`.`EstadoCivil` (`idEstadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `sapi`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idCuenta`, `idPersona`),
  INDEX `fk_Cuenta_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Cuenta_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `sapi`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `idCuenta` INT NOT NULL,
  PRIMARY KEY (`idLogin`, `idCuenta`),
  INDEX `fk_Login_Cuenta1_idx` (`idCuenta` ASC),
  CONSTRAINT `fk_Login_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `sapi`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Estudio` (
  `idEstudio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEstudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TipoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TipoEstudio` (
  `idTipoEstudio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `idEstudio` INT NOT NULL,
  PRIMARY KEY (`idTipoEstudio`, `idEstudio`),
  INDEX `fk_TipoEstudio_Estudio1_idx` (`idEstudio` ASC),
  CONSTRAINT `fk_TipoEstudio_Estudio1`
    FOREIGN KEY (`idEstudio`)
    REFERENCES `sapi`.`Estudio` (`idEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TipoCita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TipoCita` (
  `idTipoCita` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTipoCita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`CodigoPostal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`CodigoPostal` (
  `idCodigoPostal` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(5) NOT NULL,
  `idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idCodigoPostal`),
  INDEX `fk_CodigoPostal_Municipio1_idx` (`idMunicipio` ASC),
  CONSTRAINT `fk_CodigoPostal_Municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `sapi`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Escolaridad` (
  `idEscolaridad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEscolaridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `expediente` VARCHAR(45) NOT NULL,
  `seguroPopular` VARCHAR(10) NULL,
  `idCuenta` INT NOT NULL,
  `idEscolaridad` INT NOT NULL,
  `peso` DOUBLE NULL,
  `imc` DOUBLE NULL,
  `talla` DOUBLE NULL,
  `editando` TINYINT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Paciente_Cuenta1_idx` (`idCuenta` ASC),
  INDEX `fk_Paciente_Escolaridad1_idx` (`idEscolaridad` ASC),
  CONSTRAINT `fk_Paciente_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `sapi`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Escolaridad1`
    FOREIGN KEY (`idEscolaridad`)
    REFERENCES `sapi`.`Escolaridad` (`idEscolaridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `idDepartamento`),
  INDEX `fk_Medico_Cuenta1_idx` (`idCuenta` ASC),
  INDEX `fk_Medico_Departamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_Medico_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `sapi`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `sapi`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`BIRADS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`BIRADS` (
  `idBirads` INT NOT NULL AUTO_INCREMENT,
  `nombre` INT NULL,
  PRIMARY KEY (`idBirads`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`LugarBiopsia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`LugarBiopsia` (
  `idLugarBiopsia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idLugarBiopsia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idPrograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Atencion` (
  `idAtencion` INT NOT NULL AUTO_INCREMENT,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NULL,
  PRIMARY KEY (`idAtencion`, `Paciente_idPaciente`),
  INDEX `fk_Atencion_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Atencion_Medico1_idx` (`Medico_idMedico` ASC),
  CONSTRAINT `fk_Atencion_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `sapi`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atencion_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `sapi`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Receptores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Receptores` (
  `idReceptores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idReceptores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TipoHistologico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TipoHistologico` (
  `idTipoHistologico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idTipoHistologico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Biopsia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Biopsia` (
  `idBiopsia` INT NOT NULL AUTO_INCREMENT,
  `idReceptores` INT NULL,
  `idTipoHistologico` INT NULL,
  `idLugarBiopsia` INT NULL,
  PRIMARY KEY (`idBiopsia`),
  INDEX `fk_Biopsia_Receptores1_idx` (`idReceptores` ASC),
  INDEX `fk_Biopsia_TipoHistologico1_idx` (`idTipoHistologico` ASC),
  INDEX `fk_Biopsia_LugarBiopsia1_idx` (`idLugarBiopsia` ASC),
  CONSTRAINT `fk_Biopsia_Receptores1`
    FOREIGN KEY (`idReceptores`)
    REFERENCES `sapi`.`Receptores` (`idReceptores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biopsia_TipoHistologico1`
    FOREIGN KEY (`idTipoHistologico`)
    REFERENCES `sapi`.`TipoHistologico` (`idTipoHistologico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biopsia_LugarBiopsia1`
    FOREIGN KEY (`idLugarBiopsia`)
    REFERENCES `sapi`.`LugarBiopsia` (`idLugarBiopsia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`MastografiaPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`MastografiaPaciente` (
  `idMastografiaPaciente` INT NOT NULL AUTO_INCREMENT,
  `BIRADS_idBirads` INT NOT NULL,
  PRIMARY KEY (`idMastografiaPaciente`),
  INDEX `fk_MastografiaPaciente_BIRADS1_idx` (`BIRADS_idBirads` ASC),
  CONSTRAINT `fk_MastografiaPaciente_BIRADS1`
    FOREIGN KEY (`BIRADS_idBirads`)
    REFERENCES `sapi`.`BIRADS` (`idBirads`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadoCita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadoCita` (
  `idEstadoCita` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEstadoCita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`ImportanciaCita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`ImportanciaCita` (
  `idImportanciaCita` INT NOT NULL AUTO_INCREMENT,
  `importancia` INT NULL,
  PRIMARY KEY (`idImportanciaCita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `idTipoCita` INT NOT NULL,
  `Atencion_idAtencion` INT NOT NULL,
  `idEstudio` INT NULL,
  `Biopsia_idBiopsia` INT NULL,
  `MastografiaPaciente_idMastografiaPaciente` INT NULL,
  `EstadoCita_idEstadoCita` INT NOT NULL,
  `ImportanciaCita_idImportanciaCita` INT NOT NULL,
  PRIMARY KEY (`idCita`, `idTipoCita`, `Atencion_idAtencion`),
  INDEX `fk_Cita_TipoCita1_idx` (`idTipoCita` ASC),
  INDEX `fk_Cita_Atencion1_idx` (`Atencion_idAtencion` ASC),
  INDEX `fk_Cita_Estudio1_idx` (`idEstudio` ASC),
  INDEX `fk_Cita_Biopsia1_idx` (`Biopsia_idBiopsia` ASC),
  INDEX `fk_Cita_MastografiaPaciente1_idx` (`MastografiaPaciente_idMastografiaPaciente` ASC),
  INDEX `fk_Cita_EstadoCita1_idx` (`EstadoCita_idEstadoCita` ASC),
  INDEX `fk_Cita_ImportanciaCita1_idx` (`ImportanciaCita_idImportanciaCita` ASC),
  CONSTRAINT `fk_Cita_TipoCita1`
    FOREIGN KEY (`idTipoCita`)
    REFERENCES `sapi`.`TipoCita` (`idTipoCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Atencion1`
    FOREIGN KEY (`Atencion_idAtencion`)
    REFERENCES `sapi`.`Atencion` (`idAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Estudio1`
    FOREIGN KEY (`idEstudio`)
    REFERENCES `sapi`.`TipoEstudio` (`idTipoEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Biopsia1`
    FOREIGN KEY (`Biopsia_idBiopsia`)
    REFERENCES `sapi`.`Biopsia` (`idBiopsia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_MastografiaPaciente1`
    FOREIGN KEY (`MastografiaPaciente_idMastografiaPaciente`)
    REFERENCES `sapi`.`MastografiaPaciente` (`idMastografiaPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_EstadoCita1`
    FOREIGN KEY (`EstadoCita_idEstadoCita`)
    REFERENCES `sapi`.`EstadoCita` (`idEstadoCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_ImportanciaCita1`
    FOREIGN KEY (`ImportanciaCita_idImportanciaCita`)
    REFERENCES `sapi`.`ImportanciaCita` (`idImportanciaCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadoEstudio` (
  `idEstadoEstudio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idEstadoEstudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`DocumentoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`DocumentoEstudio` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `archivo` MEDIUMBLOB NOT NULL,
  `previo` TINYINT NULL,
  `EstadoEstudio_idEstadoEstudio` INT NOT NULL,
  `Atencion_idAtencion` INT NOT NULL,
  PRIMARY KEY (`idDocumento`, `EstadoEstudio_idEstadoEstudio`, `Atencion_idAtencion`),
  INDEX `fk_DocumentoEstudio_EstadoEstudio1_idx` (`EstadoEstudio_idEstadoEstudio` ASC),
  INDEX `fk_DocumentoEstudio_Atencion1_idx` (`Atencion_idAtencion` ASC),
  CONSTRAINT `fk_DocumentoEstudio_EstadoEstudio1`
    FOREIGN KEY (`EstadoEstudio_idEstadoEstudio`)
    REFERENCES `sapi`.`EstadoEstudio` (`idEstadoEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DocumentoEstudio_Atencion1`
    FOREIGN KEY (`Atencion_idAtencion`)
    REFERENCES `sapi`.`Atencion` (`idAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`LlamadaCita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`LlamadaCita` (
  `idLlamadaCita` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `llamada` TINYINT NULL,
  `idCita` INT NOT NULL,
  PRIMARY KEY (`idLlamadaCita`, `idCita`),
  INDEX `fk_LlamadaCita_Cita1_idx` (`idCita` ASC),
  CONSTRAINT `fk_LlamadaCita_Cita1`
    FOREIGN KEY (`idCita`)
    REFERENCES `sapi`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EtapaClinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EtapaClinica` (
  `idEtapaClinica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEtapaClinica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TCodificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TCodificado` (
  `idTCodificado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTCodificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`NCodificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`NCodificado` (
  `idNCodificado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNCodificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadiajeTNM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadiajeTNM` (
  `idRegistroTNM` INT NOT NULL AUTO_INCREMENT,
  `tClinico` DOUBLE NOT NULL,
  `tImagen` DOUBLE NOT NULL,
  `nTamaño` DOUBLE NOT NULL,
  `idTCodificado` INT NOT NULL,
  `idNCodificado` INT NOT NULL,
  `Metastasis` TINYINT NULL,
  PRIMARY KEY (`idRegistroTNM`),
  INDEX `fk_EstadiajeTNM_TCodificado1_idx` (`idTCodificado` ASC),
  INDEX `fk_EstadiajeTNM_NCodificado1_idx` (`idNCodificado` ASC),
  CONSTRAINT `fk_EstadiajeTNM_TCodificado1`
    FOREIGN KEY (`idTCodificado`)
    REFERENCES `sapi`.`TCodificado` (`idTCodificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EstadiajeTNM_NCodificado1`
    FOREIGN KEY (`idNCodificado`)
    REFERENCES `sapi`.`NCodificado` (`idNCodificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`RegistroDiagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`RegistroDiagnostico` (
  `idRegistroDiagnostico` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `previoDiagnostico` TINYINT NULL,
  `idPaciente` INT NOT NULL,
  `EtapaClinica_idEtapaClinica` INT NOT NULL,
  `EstadiajeTNM_idRegistroTNM` INT NOT NULL,
  PRIMARY KEY (`idRegistroDiagnostico`, `idPaciente`, `EtapaClinica_idEtapaClinica`, `EstadiajeTNM_idRegistroTNM`),
  INDEX `fk_RegistroDiagnostico_Paciente1_idx` (`idPaciente` ASC),
  INDEX `fk_RegistroDiagnostico_EtapaClinica1_idx` (`EtapaClinica_idEtapaClinica` ASC),
  INDEX `fk_RegistroDiagnostico_EstadiajeTNM1_idx` (`EstadiajeTNM_idRegistroTNM` ASC),
  CONSTRAINT `fk_RegistroDiagnostico_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `sapi`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroDiagnostico_EtapaClinica1`
    FOREIGN KEY (`EtapaClinica_idEtapaClinica`)
    REFERENCES `sapi`.`EtapaClinica` (`idEtapaClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroDiagnostico_EstadiajeTNM1`
    FOREIGN KEY (`EstadiajeTNM_idRegistroTNM`)
    REFERENCES `sapi`.`EstadiajeTNM` (`idRegistroTNM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`LugarDelCuerpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`LugarDelCuerpo` (
  `idLugarDelCuerpo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `idMetastasis` INT NOT NULL,
  PRIMARY KEY (`idLugarDelCuerpo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Sintoma` (
  `idSintoma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idSintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Paquete` (
  `idPaquete` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idPaquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(255) NULL,
  `noInterior` VARCHAR(10) NULL,
  `noExterior` VARCHAR(10) NULL,
  `colonia` VARCHAR(255) NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Direccion_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `sapi`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Medico_has_Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Medico_has_Cita` (
  `idMedico` INT NOT NULL,
  `idCita` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `idCita`, `idPaciente`),
  INDEX `fk_Medico_has_Cita_Cita1_idx` (`idCita` ASC, `idPaciente` ASC),
  INDEX `fk_Medico_has_Cita_Medico1_idx` (`idMedico` ASC),
  CONSTRAINT `fk_Medico_has_Cita_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `sapi`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Cita_Cita1`
    FOREIGN KEY (`idCita`)
    REFERENCES `sapi`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Posicion` (
  `idPosicion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPosicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Medico_has_Posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Medico_has_Posicion` (
  `idMedico` INT NOT NULL,
  `idPosicion` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `idPosicion`),
  INDEX `fk_Medico_has_Posicion_Posicion1_idx` (`idPosicion` ASC),
  INDEX `fk_Medico_has_Posicion_Medico1_idx` (`idMedico` ASC),
  CONSTRAINT `fk_Medico_has_Posicion_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `sapi`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Posicion_Posicion1`
    FOREIGN KEY (`idPosicion`)
    REFERENCES `sapi`.`Posicion` (`idPosicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Medico_has_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Medico_has_Especialidad` (
  `idMedico` INT NOT NULL,
  `idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `idEspecialidad`),
  INDEX `fk_Medico_has_Especialidad_Especialidad1_idx` (`idEspecialidad` ASC),
  INDEX `fk_Medico_has_Especialidad_Medico1_idx` (`idMedico` ASC),
  CONSTRAINT `fk_Medico_has_Especialidad_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `sapi`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Especialidad_Especialidad1`
    FOREIGN KEY (`idEspecialidad`)
    REFERENCES `sapi`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Tratamiento` (
  `idTratamiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idTratamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TipoTratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TipoTratamiento` (
  `idTipoTratamiento` INT NOT NULL AUTO_INCREMENT,
  `Tratamiento_idTratamiento` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idTipoTratamiento`, `Tratamiento_idTratamiento`),
  INDEX `fk_TipoTratamiento_Tratamiento1_idx` (`Tratamiento_idTratamiento` ASC),
  CONSTRAINT `fk_TipoTratamiento_Tratamiento1`
    FOREIGN KEY (`Tratamiento_idTratamiento`)
    REFERENCES `sapi`.`Tratamiento` (`idTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Tratamiento_has_Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Tratamiento_has_Paciente` (
  `Atencion_idAtencion` INT NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `Recurrente` TINYINT NULL,
  `TipoTratamiento_idTipoTratamiento` INT NOT NULL,
  PRIMARY KEY (`Atencion_idAtencion`, `TipoTratamiento_idTipoTratamiento`),
  INDEX `fk_Tratamiento_has_Paciente_Atencion1_idx` (`Atencion_idAtencion` ASC),
  INDEX `fk_Tratamiento_has_Paciente_TipoTratamiento1_idx` (`TipoTratamiento_idTipoTratamiento` ASC),
  CONSTRAINT `fk_Tratamiento_has_Paciente_Atencion1`
    FOREIGN KEY (`Atencion_idAtencion`)
    REFERENCES `sapi`.`Atencion` (`idAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tratamiento_has_Paciente_TipoTratamiento1`
    FOREIGN KEY (`TipoTratamiento_idTipoTratamiento`)
    REFERENCES `sapi`.`TipoTratamiento` (`idTipoTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadoPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadoPaciente` (
  `idEstadoPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idEstadoPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`EstadoPaciente_has_Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`EstadoPaciente_has_Paciente` (
  `idEstadoPaciente` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `fefcha` DATETIME NULL,
  PRIMARY KEY (`idEstadoPaciente`, `idPaciente`),
  INDEX `fk_EstadoPaciente_has_Paciente_Paciente1_idx` (`idPaciente` ASC),
  INDEX `fk_EstadoPaciente_has_Paciente_EstadoPaciente1_idx` (`idEstadoPaciente` ASC),
  CONSTRAINT `fk_EstadoPaciente_has_Paciente_EstadoPaciente1`
    FOREIGN KEY (`idEstadoPaciente`)
    REFERENCES `sapi`.`EstadoPaciente` (`idEstadoPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EstadoPaciente_has_Paciente_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `sapi`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`LugarDelCuerpo_has_EstadiajeTNM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`LugarDelCuerpo_has_EstadiajeTNM` (
  `LugarDelCuerpo_idLugarDelCuerpo` INT NOT NULL,
  `EstadiajeTNM_idRegistroTNM` INT NOT NULL,
  PRIMARY KEY (`LugarDelCuerpo_idLugarDelCuerpo`, `EstadiajeTNM_idRegistroTNM`),
  INDEX `fk_LugarDelCuerpo_has_EstadiajeTNM_EstadiajeTNM1_idx` (`EstadiajeTNM_idRegistroTNM` ASC),
  INDEX `fk_LugarDelCuerpo_has_EstadiajeTNM_LugarDelCuerpo1_idx` (`LugarDelCuerpo_idLugarDelCuerpo` ASC),
  CONSTRAINT `fk_LugarDelCuerpo_has_EstadiajeTNM_LugarDelCuerpo1`
    FOREIGN KEY (`LugarDelCuerpo_idLugarDelCuerpo`)
    REFERENCES `sapi`.`LugarDelCuerpo` (`idLugarDelCuerpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LugarDelCuerpo_has_EstadiajeTNM_EstadiajeTNM1`
    FOREIGN KEY (`EstadiajeTNM_idRegistroTNM`)
    REFERENCES `sapi`.`EstadiajeTNM` (`idRegistroTNM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Programa_has_Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Programa_has_Atencion` (
  `Programa_idPrograma` INT NOT NULL,
  `Atencion_idAtencion` INT NOT NULL,
  PRIMARY KEY (`Programa_idPrograma`, `Atencion_idAtencion`),
  INDEX `fk_Programa_has_Atencion_Atencion1_idx` (`Atencion_idAtencion` ASC),
  INDEX `fk_Programa_has_Atencion_Programa1_idx` (`Programa_idPrograma` ASC),
  CONSTRAINT `fk_Programa_has_Atencion_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `sapi`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programa_has_Atencion_Atencion1`
    FOREIGN KEY (`Atencion_idAtencion`)
    REFERENCES `sapi`.`Atencion` (`idAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Sintoma_has_Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Sintoma_has_Paquete` (
  `Sintoma_idSintoma` INT NOT NULL,
  `Paquete_idPaquete` INT NOT NULL,
  PRIMARY KEY (`Sintoma_idSintoma`, `Paquete_idPaquete`),
  INDEX `fk_Sintoma_has_Paquete_Paquete1_idx` (`Paquete_idPaquete` ASC),
  INDEX `fk_Sintoma_has_Paquete_Sintoma1_idx` (`Sintoma_idSintoma` ASC),
  CONSTRAINT `fk_Sintoma_has_Paquete_Sintoma1`
    FOREIGN KEY (`Sintoma_idSintoma`)
    REFERENCES `sapi`.`Sintoma` (`idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sintoma_has_Paquete_Paquete1`
    FOREIGN KEY (`Paquete_idPaquete`)
    REFERENCES `sapi`.`Paquete` (`idPaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Sintoma_has_Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Sintoma_has_Atencion` (
  `idSintomaAtencion` INT NOT NULL AUTO_INCREMENT,
  `idSintoma` INT NOT NULL,
  `idAtencion` INT NOT NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`idSintomaAtencion`, `idSintoma`, `idAtencion`),
  INDEX `fk_Sintoma_has_Atencion_Atencion1_idx` (`idAtencion` ASC),
  INDEX `fk_Sintoma_has_Atencion_Sintoma1_idx` (`idSintoma` ASC),
  CONSTRAINT `fk_Sintoma_has_Atencion_Sintoma1`
    FOREIGN KEY (`idSintoma`)
    REFERENCES `sapi`.`Sintoma` (`idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sintoma_has_Atencion_Atencion1`
    FOREIGN KEY (`idAtencion`)
    REFERENCES `sapi`.`Atencion` (`idAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`RegistroSintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`RegistroSintoma` (
  `idRegistroSintoma` INT NOT NULL AUTO_INCREMENT,
  `idSintomaAtencion` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idRegistroSintoma`, `idSintomaAtencion`),
  INDEX `fk_RegistroSintoma_Sintoma_has_Atencion1_idx` (`idSintomaAtencion` ASC),
  CONSTRAINT `fk_RegistroSintoma_Sintoma_has_Atencion1`
    FOREIGN KEY (`idSintomaAtencion`)
    REFERENCES `sapi`.`Sintoma_has_Atencion` (`idSintomaAtencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Farmaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Farmaco` (
  `idFarmaco` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idFarmaco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`Farmaco_has_TipoTratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`Farmaco_has_TipoTratamiento` (
  `idFarmacoTipoTratamiento` INT NOT NULL AUTO_INCREMENT,
  `Farmaco_idFarmaco` INT NOT NULL,
  `TipoTratamiento_idTipoTratamiento` INT NOT NULL,
  PRIMARY KEY (`idFarmacoTipoTratamiento`, `Farmaco_idFarmaco`, `TipoTratamiento_idTipoTratamiento`),
  INDEX `fk_Farmaco_has_TipoTratamiento_TipoTratamiento1_idx` (`TipoTratamiento_idTipoTratamiento` ASC),
  INDEX `fk_Farmaco_has_TipoTratamiento_Farmaco1_idx` (`Farmaco_idFarmaco` ASC),
  CONSTRAINT `fk_Farmaco_has_TipoTratamiento_Farmaco1`
    FOREIGN KEY (`Farmaco_idFarmaco`)
    REFERENCES `sapi`.`Farmaco` (`idFarmaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Farmaco_has_TipoTratamiento_TipoTratamiento1`
    FOREIGN KEY (`TipoTratamiento_idTipoTratamiento`)
    REFERENCES `sapi`.`TipoTratamiento` (`idTipoTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`ComentarioCita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`ComentarioCita` (
  `idComentarioCita` INT NOT NULL AUTO_INCREMENT,
  `comentario` MEDIUMTEXT NULL,
  `Cita_idCita` INT NOT NULL,
  `navegadora` TINYINT NULL,
  PRIMARY KEY (`idComentarioCita`),
  INDEX `fk_ComentarioCita_Cita1_idx` (`Cita_idCita` ASC),
  CONSTRAINT `fk_ComentarioCita_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `sapi`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapi`.`DocumentosIniciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`DocumentosIniciales` (
  `idDocumentosIniciales` INT NOT NULL AUTO_INCREMENT,
  `archivo` MEDIUMBLOB NULL,
  `comentario` MEDIUMTEXT NULL,
  `TipoDocumento_idTipoDocumento` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idDocumentosIniciales`, `TipoDocumento_idTipoDocumento`, `Paciente_idPaciente`),
  INDEX `fk_DocumentosIniciales_TipoDocumento1_idx` (`TipoDocumento_idTipoDocumento` ASC),
  INDEX `fk_DocumentosIniciales_Paciente1_idx` (`Paciente_idPaciente` ASC),
  CONSTRAINT `fk_DocumentosIniciales_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento_idTipoDocumento`)
    REFERENCES `sapi`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DocumentosIniciales_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `sapi`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
